title: Python 
author: Michał
email:
description: notatki z nauki
url: "https://mgurg.github.io" 

# Build settings
remote_theme: huangyz0918/moving

plugins:
  - jekyll-feed

moving:
  about_you: notatki z nauki
  avatar_url: https://roboticsbook.com/mgurg.jpg
  date_format: "%b %d"
  back_to: "Index"
  social_links:
    rss: RSS
    github:  mgurg
    facebook: 
    linkedin: michal-gurgul

