title: Python 
author: Michał
email: donotemailme@gmail.com
description: notatki z nauki
url: "https://mgurg.github.io" 

# Build settings
remote_theme: huangyz0918/moving

plugins:
  - jekyll-feed

moving:
  about_you: notatki z nauki
  avatar_url: https://i.loli.net/2019/09/07/wiBh3uMWRUaLX5K.png 
  date_format: "%b %d"
  back_to: "Index"
  social_links:
    rss: RSS
    github:  mgurg
    facebook: 
    linkedin: 

